exec(open("experiment1.py").read())
exec(open("plotting_experiment1.py").read())
exec(open("experiment2.py").read())
exec(open("plotting_experiment2.py").read())
exec(open("experiment3.py").read())
exec(open("plotting_experiment3.py").read())
